# Site settings
title: "Mari Kwee's Website"
description: "Mari Kwee's Resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Mari Kwee"
resume_title:                   "Software Developer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "marikwee12@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "808-687-1364"
resume_contact_address:         "1223 E Cherry Street Seattle, WA"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi, my name is Mari Kwee. I am a Software Developer at Hawaiian Airlines with a strong background in designing and optimizing backend systems.
I play a key role in improving the loyalty systems, where I have reduced accrual discrepancies from 20% to less than 1%.
I have developed automated workers and monitoring tools that enhance system performace and data accuracy.
I have extensive knowledge of the loyalty systems at Hawaiian Airlines along with a deepened understanding of working at an airlines company as a whole. 
I graduated from Seattle University in June of 2023 with a major in Computer Science and minor in Data Science. 
I am passionate about problem solving, collaboration, and mentorship.
I am interested in data analytics, machine learning, artificial intelligence, software development, and UX design.
Please feel free to contact me at marikwee12@gmail.com below.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://https://github.com/marikwee"
  #resume_twitter_url:           "http://twitter.com/jglovier"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/mari-kwee-98b668203/"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
